# Schema for the configuration files of the FED - Digital Analytics Program Government-wide Code module.
fed_dap.settings:
  type: config_object
  label: 'FED - Digital Analytics Program Government-wide Code settings'
  mapping:
    param_agency:
      type: string
      label: 'Agency'
    param_subagency:
      type: string
      label: 'Sub Agency'
    param_sitetopic:
      type: string
      label: 'Site Topic'
    param_siteplatform:
      type: string
      label: 'Site Platform'
    js_library:
      type: string
      label: 'Selected JavaScript Library Source'